<?php

use Drupal\commerce_order\Entity\OrderInterface;

/**
 * Implements hook_cron().
 */
function bigcommerce_stock_cron() {
  \Drupal::service('bigcommerce_stock.cron')->run();
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function bigcommerce_stock_commerce_order_delete(OrderInterface $order) {
  // In case a cart is deleted remove all reserved stock.
  if (empty($order->cart->value)) {
    return;
  }

  $location = current(\Drupal::entityTypeManager()
    ->getStorage('commerce_stock_location')
    ->loadByProperties(['type' => 'bigcommerce']));

  \Drupal::database()->delete('commerce_stock_transaction')
    ->condition('related_oid', $order->id())
    ->condition('location_id', $location->id())
    ->execute();
}
