bigcommerce.settings:
  type: config_object
  label: 'BigCommerce config settings'
  mapping:
    api:
      type: mapping
      label: 'BigCommerce API settings'
      mapping:
        path:
          type: uri
          label: 'BigCommerce API Path'
        access_token:
          type: string
          label: 'BigCommerce API Access Token'
        client_id:
          type: string
          label: 'BigCommerce API Client ID'
        client_secret:
          type: string
          label: 'BigCommerce API Client Secret'
        timeout:
          type: integer
          label: 'BigCommerce API cURL timeout'
    channel:
      type: mapping
      label: 'BigCommerce channel settings'
      mapping:
        id:
          type: string
          label: 'BigCommerce API Channel ID'
        name:
          type: string
          label: 'BigCommerce API Channel Name'
        site_id:
          type: string
          label: 'BigCommerce API Site ID'
        site_url:
          type: uri
          label: 'BigCommerce API Site URL'
