bigcommerce_stock.settings:
  type: config_object
  label: 'BigCommerce Stock config settings'
  mapping:
    id:
      type: integer
      label: 'BigCommerce Stock webhook ID'
    destination:
      type: string
      label: 'BigCommerce Stock webhook destination'
    username:
      type: string
      label: 'BigCommerce Stock webhook username'
    password:
      type: string
      label: 'BigCommerce Stock webhook password'
